// Seed — canonical mandatory label phrases (admin-managed catalog).
//
// Replaces the ad-hoc `disclosures` JSON with a curated, editable catalog the
// compliance scanner + label renderer can reference. Starter set spans the
// categories (allergen / disclaimer / warning / identity) and labeling types.
// Idempotent (upsert by slug). FINAL legal text should be counsel-reviewed.

import { PrismaClient } from '@prisma/client'
import type { MandatoryPhraseCategory } from '@prisma/client'

interface PhraseSeed {
  slug: string
  title: string
  body: string
  category: MandatoryPhraseCategory
  /** MANDATORY = regulatory requirement; RECOMMENDED = optional marketing/advisory. Defaults MANDATORY. */
  requirement?: 'MANDATORY' | 'RECOMMENDED'
  labelingTypes: string[]
  cfrCitation?: string
  appliesWhen?: string
}

const PHRASES: PhraseSeed[] = [
  {
    slug: 'dshea-disclaimer',
    title: 'DSHEA Disclaimer',
    body: 'These statements have not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease.',
    category: 'DISCLAIMER',
    labelingTypes: ['DIETARY_SUPPLEMENT'],
    cfrCitation: '21 CFR 101.93(b)',
    appliesWhen: 'A structure/function claim appears on the label.',
  },
  {
    slug: 'iron-overdose-warning',
    title: 'Iron Overdose Warning',
    body: 'Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children under 6. Keep this product out of reach of children. In case of accidental overdose, call a doctor or poison control center immediately.',
    category: 'WARNING',
    labelingTypes: ['DIETARY_SUPPLEMENT', 'FOOD'],
    cfrCitation: '21 CFR 101.17(e)',
    appliesWhen: '≥30 mg iron per serving in a solid oral dosage form.',
  },
  {
    slug: 'allergen-contains-statement',
    title: 'Allergen "Contains" Statement',
    body: 'Contains: [list each major food allergen present, e.g. Milk, Eggs, Wheat, Soy, Peanuts, Tree Nuts, Fish, Crustacean Shellfish, Sesame].',
    category: 'ALLERGEN',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT'],
    cfrCitation: '21 USC 343(w) (FALCPA); sesame added by FASTER Act, 21 USC 321(qq)',
    appliesWhen:
      'The product contains one of the 9 major allergens (milk, egg, fish, Crustacean shellfish, tree nuts, peanuts, wheat, soybeans, sesame — sesame mandatory since Jan 1 2023). Either declare the source in the ingredient list (e.g. "lecithin (soy)") OR use a "Contains" statement adjacent to the ingredient list. Mollusks are NOT major allergens.',
  },
  {
    slug: 'keep-out-of-reach-children',
    title: 'Keep Out of Reach of Children',
    body: 'Keep out of reach of children. In case of overdose, get medical help or contact a Poison Control Center right away.',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(x)',
    appliesWhen: 'All OTC drug products.',
  },
  {
    slug: 'phenylketonurics',
    title: 'Phenylketonurics Warning',
    body: 'PHENYLKETONURICS: CONTAINS PHENYLALANINE.',
    category: 'WARNING',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE'],
    cfrCitation: '21 CFR 172.804(g); alcohol: 27 CFR 5.63(c)/7.63(b)(4)',
    appliesWhen:
      'The product contains aspartame. Must appear in capital letters, separate and apart from other information (TTB requires this on alcohol beverages too).',
  },
  {
    slug: 'bioengineered-disclosure',
    title: 'Bioengineered Food Disclosure',
    body: 'Contains a bioengineered food ingredient.',
    category: 'DISCLAIMER',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT'],
    cfrCitation: '7 CFR 66 (USDA NBFDS)',
    appliesWhen: 'The product contains a detectable bioengineered ingredient.',
  },
  {
    slug: 'otc-acetaminophen-liver-warning',
    title: 'OTC Liver Warning (Acetaminophen)',
    body: 'Liver warning: This product contains acetaminophen. Severe liver damage may occur if you take more than the maximum daily amount, with other drugs containing acetaminophen, or 3 or more alcoholic drinks every day while using this product.',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.326',
    appliesWhen: 'Acetaminophen is an active ingredient.',
  },
  {
    slug: 'manufacturer-distributor-statement',
    title: 'Manufacturer / Distributor Statement',
    body: 'Manufactured for: [Brand Name], [City, State, ZIP].',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'OTC'],
    cfrCitation: '21 CFR 101.5',
    appliesWhen: 'All packaged products — name + place of business of the responsible firm.',
  },
  {
    slug: 'aafco-nutritional-adequacy',
    title: 'AAFCO Nutritional Adequacy Statement',
    body: '[Product Name] is formulated to meet the nutritional levels established by the AAFCO Dog (or Cat) Food Nutrient Profiles for [life stage].',
    category: 'DISCLAIMER',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO Model Pet Food Reg. PF5(a)(3)(F)(i)(aa)',
    appliesWhen:
      'Pet food labeled "complete and balanced" (formulation method). For DOG food where life stage includes Growth or All Life Stages, append verbatim "including growth of large size dogs (70 lb. or more as an adult)" OR "except for growth of large size dogs (70 lb. or more as an adult)". AAFCO is model reg adopted state-by-state, not federal CFR.',
  },
  // ---- Brought over from the Studio's hardcoded phrase chips (compliance-relevant) ----
  {
    slug: 'allergen-may-contain',
    title: 'Allergen "May Contain" Advisory',
    body: 'May contain traces of [allergens, e.g. tree nuts, peanuts].',
    category: 'ALLERGEN',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE'],
    cfrCitation: '21 CFR 101 (advisory)',
    appliesWhen: 'Shared-line cross-contact is possible.',
  },
  {
    slug: 'alcohol-government-warning',
    title: 'Alcohol Government Warning',
    body: 'GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.',
    category: 'WARNING',
    labelingTypes: ['BEVERAGE', 'FOOD'],
    cfrCitation: '27 CFR 16.21',
    appliesWhen: 'Alcoholic beverage ≥ 0.5% ABV.',
  },
  {
    slug: 'tamper-evident-seal',
    title: 'Tamper-Evident Seal Notice',
    body: 'Do not use if the printed safety seal under the cap is broken or missing.',
    category: 'WARNING',
    labelingTypes: ['DIETARY_SUPPLEMENT', 'OTC', 'FOOD'],
    cfrCitation: '21 CFR 211.132',
    appliesWhen: 'Tamper-evident packaging.',
  },
  {
    slug: 'supplement-pregnancy-consult',
    title: 'Pregnancy / Medication Consult',
    body: 'If you are pregnant, nursing, taking medication, or have a medical condition, consult your healthcare provider before use.',
    category: 'WARNING',
    labelingTypes: ['DIETARY_SUPPLEMENT'],
    appliesWhen: 'Dietary supplements (advisory).',
  },
  {
    slug: 'discontinue-if-irritation',
    title: 'Discontinue If Adverse Reaction',
    body: 'Discontinue use and consult a doctor if any adverse reaction or irritation occurs.',
    category: 'WARNING',
    labelingTypes: ['DIETARY_SUPPLEMENT', 'COSMETIC'],
    appliesWhen: 'Topical or ingestible products (advisory).',
  },
  {
    slug: 'storage-refrigerate-after-opening',
    title: 'Storage — Refrigerate After Opening',
    body: 'Refrigerate after opening. Use within [N] days.',
    category: 'DIRECTIONS',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    appliesWhen: 'Perishable after opening.',
  },
  {
    slug: 'storage-cool-dry-place',
    title: 'Storage — Cool, Dry Place',
    body: 'Store in a cool, dry place away from direct sunlight.',
    category: 'DIRECTIONS',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE'],
    appliesWhen: 'Shelf-stable products.',
  },
  {
    slug: 'net-quantity-statement',
    title: 'Net Quantity of Contents',
    body: 'Net Wt [X] oz ([Y] g) — US customary first, metric in parentheses, placed in the bottom 30% of the principal display panel.',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'PET_PRODUCT', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.105',
    appliesWhen: 'All packaged products.',
  },
  {
    slug: 'ingredient-statement',
    title: 'Ingredient Statement',
    body: 'Ingredients: [list every ingredient in descending order of predominance by weight, using common or usual names].',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.4',
    appliesWhen: 'Multi-ingredient products.',
  },
  {
    slug: 'sulfites-declaration',
    title: 'Sulfites Declaration',
    body: 'Contains Sulfites.',
    category: 'ALLERGEN',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: 'Food: 21 CFR 101.100(a)(4) + 130.9. Alcohol (TTB governs): 27 CFR 4.32(e)/5.63(c)/7.63(b)(3)',
    appliesWhen:
      '≥10 ppm total SO₂ in the finished product. Accepted wording: "Contains Sulfites", "Contains (a) sulfiting agent(s)", or naming the agent. TTB governs alcohol ≥7% ABV; FDA governs <7% ABV.',
  },

  // ===========================================================================
  // MANDATORY — added 2026-06-05 after a full regulatory audit across FDA
  // (21 CFR 101/201/701/740), USDA (7 CFR 66), TTB (27 CFR 4/5/7/16), AAFCO
  // model regs, FALCPA/FASTER, and MoCRA 2022. Verbatim text taken from eCFR /
  // Cornell LII / govinfo; FINAL on-label text MUST be counsel-reviewed.
  // ===========================================================================

  // ---- FDA conventional food (21 CFR 101) — the rest of the mandatory set ----
  {
    slug: 'statement-of-identity',
    title: 'Statement of Identity',
    body: '[Common or usual name of the food] — shown on the principal display panel, in bold type, in a size reasonably related to the most prominent printed matter, generally parallel to the base of the package.',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.3',
    appliesWhen: 'Every packaged food/beverage (one of the 5 mandatory elements).',
  },
  {
    slug: 'nutrition-facts-panel',
    title: 'Nutrition Facts Panel',
    body: 'Nutrition Facts panel formatted per 21 CFR 101.9 (serving size, servings per container, calories, nutrients, %DV). Rendered as a structured panel — this is a mandatory element, not optional copy.',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.9',
    appliesWhen: 'Every packaged food/beverage unless a small-business exemption under 101.9(j) applies.',
  },
  {
    slug: 'juice-percentage-declaration',
    title: 'Percent Juice Declaration',
    body: 'Contains [X]% [name] juice. (Under 1%: "Contains less than 1 percent juice". No juice but juice-like: "Contains 0% juice".)',
    category: 'IDENTITY',
    labelingTypes: ['BEVERAGE'],
    cfrCitation: '21 CFR 101.30',
    appliesWhen: 'Beverage bears the name/picture of a fruit or vegetable, or color+flavor suggesting juice — even if it contains zero juice.',
  },
  {
    slug: 'unpasteurized-juice-warning',
    title: 'Unpasteurized Juice Warning',
    body: 'WARNING: This product has not been pasteurized and, therefore, may contain harmful bacteria that can cause serious illness in children, the elderly, and persons with weakened immune systems.',
    category: 'WARNING',
    labelingTypes: ['BEVERAGE'],
    cfrCitation: '21 CFR 101.17(g)',
    appliesWhen: 'Juice that has NOT been processed to a 5-log pathogen reduction, sold in package form to consumers. "WARNING" bold; statement boxed by hairlines.',
  },
  {
    slug: 'self-pressurized-food-warning',
    title: 'Self-Pressurized (Aerosol) Food Warning',
    body: 'WARNING—Avoid spraying in eyes. Contents under pressure. Do not puncture or incinerate. Do not store at temperature above 120 °F. Keep out of reach of children.',
    category: 'WARNING',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.17(a)',
    appliesWhen: 'Food packaged in a self-pressurized (aerosol) container (e.g. whipped cream). Add 101.17(b) inhalation warning if propellant is halocarbon/hydrocarbon.',
  },
  {
    slug: 'protein-weight-reduction-warning',
    title: 'Protein / Very-Low-Calorie Diet Warning',
    body: 'WARNING: Very low calorie protein diets (below 400 Calories per day) may cause serious illness or death. Do Not Use for Weight Reduction in Such Diets Without Medical Supervision. Not for use by infants, children, or pregnant or nursing women.',
    category: 'WARNING',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.17(d)(1)',
    appliesWhen: 'Protein products represented for use in reducing weight.',
  },
  {
    slug: 'fdc-yellow-5-declaration',
    title: 'FD&C Yellow No. 5 Declaration',
    body: 'FD&C Yellow No. 5 — must be listed by this specific name in the ingredient statement (cannot be hidden under "artificial color"). Certified colors (incl. FD&C Yellow No. 6) must be declared by their specific name.',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: '21 CFR 74.705 + 101.22(k)(1)',
    appliesWhen: 'Food contains FD&C Yellow No. 5 (or another certified color additive).',
  },
  {
    slug: 'artificial-flavor-declaration',
    title: 'Artificial Flavor Declaration',
    body: 'Artificial [flavor] / Artificially Flavored [flavor] — the characterizing-flavor name on the principal display panel must carry "artificial" in letters ≥ half the height of the flavor-name letters.',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.22(i)',
    appliesWhen: 'A characterizing flavor is simulated or reinforced by artificial flavor.',
  },
  {
    slug: 'chemical-preservative-declaration',
    title: 'Chemical Preservative Function Declaration',
    body: '[Preservative common name] ([function], e.g. "to retard spoilage" / "a mold inhibitor" / "to promote color retention").',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.22(j)',
    appliesWhen: 'Food contains a chemical preservative — both the name AND its function must appear.',
  },
  {
    slug: 'country-of-origin-marking',
    title: 'Country of Origin Marking',
    body: 'Product of [Country] / Made in [Country] — conspicuous, legible, indelible, permanent. Enforced by CBP.',
    category: 'IDENTITY',
    labelingTypes: ['FOOD', 'BEVERAGE', 'DIETARY_SUPPLEMENT', 'COSMETIC'],
    cfrCitation: '19 USC 1304 + 19 CFR Part 134',
    appliesWhen: 'Article of foreign origin imported into the US (or substantially transformed abroad).',
  },
  {
    slug: 'gluten-free-wheat-processed-statement',
    title: 'Gluten-Free "Wheat Processed" Statement',
    body: 'The wheat has been processed to allow this food to meet the Food and Drug Administration (FDA) requirements for gluten-free foods.',
    category: 'DISCLAIMER',
    labelingTypes: ['FOOD', 'BEVERAGE', 'DIETARY_SUPPLEMENT'],
    cfrCitation: '21 CFR 101.91',
    appliesWhen: 'A "gluten-free" claim is made AND wheat appears in the ingredient list (conditional-mandatory asterisk statement).',
  },

  // ---- Dietary supplements (21 CFR 101.36 / 101.93 / DSHEA / FDAAA 2006) ----
  {
    slug: 'supplement-statement-of-identity',
    title: 'Dietary Supplement Statement of Identity',
    body: '[Product Name] — Dietary Supplement. (The word "dietary" may be replaced by the ingredient type, e.g. "Calcium Supplement", "Herbal Supplement" — but the word "supplement" is required.)',
    category: 'IDENTITY',
    labelingTypes: ['DIETARY_SUPPLEMENT'],
    cfrCitation: '21 CFR 101.3(g)',
    appliesWhen: 'Every dietary supplement — "supplement" must appear in the statement of identity on the PDP.',
  },
  {
    slug: 'supplement-adverse-event-contact',
    title: 'Serious Adverse Event Reporting Contact',
    body: 'A domestic address or domestic phone number (with area code) through which the responsible firm can receive reports of serious adverse events. Required on the label.',
    category: 'IDENTITY',
    labelingTypes: ['DIETARY_SUPPLEMENT'],
    cfrCitation: 'FD&C Act §403(y) (21 USC 343(y)) — Dietary Supplement & Nonprescription Drug Consumer Protection Act 2006',
    appliesWhen: 'Every dietary supplement. Absence = misbranding. An existing US address/phone on the label can satisfy this.',
  },
  {
    slug: 'supplement-dv-not-established',
    title: 'Supplement Facts — "Daily Value not established" Footnote',
    body: '† Daily Value not established. (Place the symbol in the %DV column for each dietary ingredient that has no established RDI/DRV.)',
    category: 'DISCLAIMER',
    labelingTypes: ['DIETARY_SUPPLEMENT'],
    cfrCitation: '21 CFR 101.36(b)(3)(iv)',
    appliesWhen: 'Supplement Facts panel lists any dietary ingredient lacking an established Daily Value.',
  },
  {
    slug: 'psyllium-choking-notice',
    title: 'Psyllium Choking Notice',
    body: 'NOTICE: This food should be eaten with at least a full glass of liquid. Eating this product without enough liquid may cause choking. Do not eat this product if you have difficulty in swallowing.',
    category: 'WARNING',
    labelingTypes: ['DIETARY_SUPPLEMENT', 'FOOD'],
    cfrCitation: '21 CFR 101.17(f)',
    appliesWhen: 'Product contains dry/incompletely hydrated psyllium husk AND bears the soluble-fiber/CHD health claim.',
  },

  // ---- OTC drugs — Drug Facts panel (21 CFR 201.66) ----
  {
    slug: 'otc-drug-facts-title',
    title: 'Drug Facts (panel title)',
    body: 'Drug Facts (use "Drug Facts (continued)" atop continuation panels).',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(1)',
    appliesWhen: 'Every OTC drug product.',
  },
  {
    slug: 'otc-active-ingredient',
    title: 'Active Ingredient(s) heading',
    body: 'Active ingredient (in each [dosage unit]): [established name] [quantity per dosage unit].',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(2)',
    appliesWhen: 'Every OTC drug product.',
  },
  {
    slug: 'otc-purpose',
    title: 'Purpose heading',
    body: 'Purpose: [pharmacological category / principal intended action of each active ingredient].',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(3)',
    appliesWhen: 'Every OTC drug product.',
  },
  {
    slug: 'otc-uses',
    title: 'Uses heading',
    body: 'Uses: [indication(s) for the product].',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(4)',
    appliesWhen: 'Every OTC drug product.',
  },
  {
    slug: 'otc-warnings-heading',
    title: 'Warnings heading',
    body: 'Warnings (nothing else may share this line; the warnings then follow in the fixed 201.66 order).',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)',
    appliesWhen: 'Every OTC drug product with any warning.',
  },
  {
    slug: 'otc-for-external-use-only',
    title: 'For External Use Only',
    body: 'For external use only. (Variant: "For rectal use only" / "For vaginal use only".)',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(i)',
    appliesWhen: 'Topical, non-ingested OTC drug.',
  },
  {
    slug: 'otc-do-not-use',
    title: 'Do Not Use',
    body: 'Do not use [absolute contraindications under which the product should not be used].',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(iii)',
    appliesWhen: 'Absolute contraindications exist.',
  },
  {
    slug: 'otc-ask-a-doctor',
    title: 'Ask a Doctor Before Use If',
    body: 'Ask a doctor before use if you have [pre-existing condition warnings]. (Child variant: "Ask a doctor before use if the child has".)',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(iv)',
    appliesWhen: 'Pre-existing-condition or symptom warnings apply.',
  },
  {
    slug: 'otc-ask-doctor-pharmacist',
    title: 'Ask a Doctor or Pharmacist Before Use If',
    body: 'Ask a doctor or pharmacist before use if you are [taking interacting drugs]. (Child variant: "…if the child is".)',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(v)',
    appliesWhen: 'Drug-drug / drug-food interaction warnings apply.',
  },
  {
    slug: 'otc-when-using',
    title: 'When Using This Product',
    body: 'When using this product [side effects; substances or activities to avoid].',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(vi)',
    appliesWhen: 'Product has side effects or avoid-while-using cautions.',
  },
  {
    slug: 'otc-stop-use',
    title: 'Stop Use and Ask a Doctor If',
    body: 'Stop use and ask a doctor if [signs of toxicity / conditions requiring discontinuation].',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(vii)',
    appliesWhen: 'Signs requiring the consumer to stop use exist.',
  },
  {
    slug: 'otc-pregnancy-breastfeeding',
    title: 'Pregnancy / Breast-Feeding Warning (OTC)',
    body: 'If pregnant or breast-feeding, ask a health professional before use.',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(ix) / 201.63(a)',
    appliesWhen: 'Systemically-absorbed OTC drug. First four words in bold.',
  },
  {
    slug: 'otc-fda-adverse-event-line',
    title: 'OTC FDA Adverse Event Reporting Line',
    body: 'You may report side effects to FDA at 1-800-FDA-1088. (Phone min 6-point bold.)',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(5)(vii)',
    appliesWhen: 'Product is marketed under an approved NDA/ANDA AND the package has no toll-free number for reporting to the manufacturer.',
  },
  {
    slug: 'otc-reyes-syndrome-warning',
    title: "Reye's Syndrome Warning",
    body: "Reye's syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness.",
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.314(h)(1) (via 201.66(c)(5)(ii)(A))',
    appliesWhen: 'Product contains salicylates (incl. aspirin).',
  },
  {
    slug: 'otc-directions',
    title: 'Directions heading',
    body: 'Directions: [dosage + administration; table format when ≥3 age groups].',
    category: 'DIRECTIONS',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(6)',
    appliesWhen: 'Every OTC drug product.',
  },
  {
    slug: 'otc-other-information',
    title: 'Other Information heading',
    body: 'Other information [e.g. storage conditions, required content statements such as sodium/calcium/phenylalanine].',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(7)',
    appliesWhen: 'Required/optional "other information" exists.',
  },
  {
    slug: 'otc-inactive-ingredients',
    title: 'Inactive Ingredients heading',
    body: 'Inactive ingredients [established names, in alphabetical order].',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(8)',
    appliesWhen: 'Product contains any inactive ingredients.',
  },
  {
    slug: 'otc-questions',
    title: 'Questions or Comments? line',
    body: 'Questions or comments? [telephone number of a source to answer questions]. (Phone min 6-point bold.)',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.66(c)(9)',
    appliesWhen: 'Optional heading, but if no manufacturer complaint number appears anywhere on the package, the FDA reporting line becomes mandatory.',
  },
  {
    slug: 'otc-sunscreen-skin-cancer-alert',
    title: 'Sunscreen Skin Cancer / Skin Aging Alert',
    body: 'Skin Cancer/Skin Aging Alert: Spending time in the sun increases your risk of skin cancer and early skin aging. This product has been shown only to help prevent sunburn, not skin cancer or early skin aging.',
    category: 'WARNING',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.327(d)(2)',
    appliesWhen: 'Sunscreen with SPF 2–14 OR not Broad Spectrum.',
  },
  {
    slug: 'otc-sunscreen-use',
    title: 'Sunscreen Use Statement',
    body: 'Uses: helps prevent sunburn. [Broad Spectrum SPF 15+ may add:] if used as directed with other sun protection measures, decreases the risk of skin cancer and early skin aging caused by the sun.',
    category: 'IDENTITY',
    labelingTypes: ['OTC'],
    cfrCitation: '21 CFR 201.327(c)',
    appliesWhen: 'All sunscreen drug products.',
  },

  // ---- Cosmetics (21 CFR 701 / 740) + MoCRA 2022 ----
  {
    slug: 'cosmetic-statement-of-identity',
    title: 'Cosmetic Statement of Identity',
    body: '[Common, descriptive, or fanciful name of the cosmetic, e.g. "Hydrating Face Cream"] — on the principal display panel.',
    category: 'IDENTITY',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 701.11(a)',
    appliesWhen: 'Every cosmetic in package form.',
  },
  {
    slug: 'cosmetic-net-quantity',
    title: 'Cosmetic Net Quantity of Contents',
    body: 'Net wt [X] oz ([Y] g) for solids; [X] fl oz ([Y] mL) for liquids — dual US/metric, in the bottom 30% of the principal display panel.',
    category: 'IDENTITY',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 701.13(a)',
    appliesWhen: 'Every cosmetic in package form.',
  },
  {
    slug: 'cosmetic-name-place-of-business',
    title: 'Cosmetic Name & Place of Business',
    body: '[Company name], [city, state, ZIP]. If the named firm did not make the product, prefix with "Manufactured for" or "Distributed by".',
    category: 'IDENTITY',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 701.12(a),(c)',
    appliesWhen: 'Every cosmetic; the qualifier applies when the brand owner is not the manufacturer (the default for iLaunchify creators).',
  },
  {
    slug: 'cosmetic-ingredient-declaration',
    title: 'Cosmetic Ingredient Declaration (INCI)',
    body: 'Ingredients: [each ingredient by INCI/established name in descending order of predominance; ≤1% ingredients and colorants may follow in any order]. Trade-secret ingredients: "and other ingredients".',
    category: 'IDENTITY',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 701.3(a)',
    appliesWhen: 'Retail cosmetics (professional-only products are exempt from 701.3).',
  },
  {
    slug: 'cosmetic-safety-not-determined',
    title: 'Cosmetic Safety Not Determined Warning',
    body: 'Warning—The safety of this product has not been determined.',
    category: 'WARNING',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 740.10',
    appliesWhen: 'Any cosmetic whose safety has not been adequately substantiated before marketing.',
  },
  {
    slug: 'cosmetic-aerosol-warning',
    title: 'Cosmetic Aerosol Warning',
    body: 'Warning—Avoid spraying in eyes. Contents under pressure. Do not puncture or incinerate. Do not store at temperature above 120 °F. Keep out of reach of children. [Halocarbon/hydrocarbon propellant adds:] Use only as directed. Intentional misuse by deliberately concentrating and inhaling the contents can be harmful or fatal.',
    category: 'WARNING',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 740.11',
    appliesWhen: 'Cosmetic in a self-pressurized (aerosol) container.',
  },
  {
    slug: 'cosmetic-suntanning-no-sunscreen',
    title: 'Suntanning Preparation (No Sunscreen) Warning',
    body: 'Warning—This product does not contain a sunscreen and does not protect against sunburn. Repeated exposure of unprotected skin while tanning may increase the risk of skin aging, skin cancer, and other harmful effects to the skin even if you do not burn.',
    category: 'WARNING',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 740.19',
    appliesWhen: 'Suntanning preparation (tanning oil/lotion, incl. for tanning beds) without a sunscreen ingredient.',
  },
  {
    slug: 'cosmetic-feminine-deodorant-spray',
    title: 'Feminine Deodorant Spray Caution',
    body: 'Caution—For external use only. Spray at least 8 inches from skin. Do not apply to broken, irritated, or itching skin. Persistent, unusual odor or discharge may indicate conditions for which a physician should be consulted. Discontinue use immediately if rash, irritation, or discomfort develops.',
    category: 'WARNING',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 740.12',
    appliesWhen: 'Feminine deodorant sprays.',
  },
  {
    slug: 'cosmetic-foaming-bath-caution',
    title: 'Foaming Detergent Bath Caution',
    body: 'Caution—Use only as directed. Excessive use or prolonged exposure may cause irritation to skin and urinary tract. Discontinue use if rash, redness, or itching occurs. Consult your physician if irritation persists. Keep out of reach of children.',
    category: 'WARNING',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 740.17',
    appliesWhen: 'Foaming detergent bath products (bubble bath).',
  },
  {
    slug: 'cosmetic-coal-tar-hair-dye',
    title: 'Coal-Tar Hair Dye Warning',
    body: 'Warning—Contains an ingredient that can penetrate your skin and has been determined to cause cancer in laboratory animals. Caution—This product contains ingredients which may cause skin irritation on certain individuals and a preliminary test according to accompanying directions should first be made. This product must not be used for dyeing the eyelashes or eyebrows; to do so may cause blindness.',
    category: 'WARNING',
    labelingTypes: ['COSMETIC'],
    cfrCitation: '21 CFR 740.18 + FD&C Act §601(a)',
    appliesWhen: 'Coal-tar hair dyes containing the specified ingredient.',
  },
  {
    slug: 'cosmetic-mocra-adverse-event-contact',
    title: 'MoCRA Adverse Event Reporting Contact',
    body: 'A domestic address, domestic phone number, or electronic contact (which may include a website) through which the responsible person can receive adverse event reports. At least one must appear on the label.',
    category: 'IDENTITY',
    labelingTypes: ['COSMETIC'],
    cfrCitation: 'FD&C Act §609 (21 USC 364c) — MoCRA 2022',
    appliesWhen: 'Every cosmetic product. In force (statutory 2024-12-29; FDA enforcement from 2025-07-01).',
  },
  {
    slug: 'cosmetic-mocra-professional-use',
    title: 'MoCRA Professional-Use Statement',
    body: 'For professional use only. This product shall be administered or used only by licensed professionals.',
    category: 'WARNING',
    labelingTypes: ['COSMETIC'],
    cfrCitation: 'FD&C Act §605 — MoCRA 2022',
    appliesWhen: 'Cosmetic intended to be used only by licensed professionals (salon/spa back-bar). A bare "Professional use only" is insufficient.',
  },

  // ---- Pet food (AAFCO model regs + 21 CFR 501) ----
  {
    slug: 'pet-species-designation',
    title: 'Pet Food Species Designation',
    body: 'Dog Food / Cat Food (intended-use statement on the principal display panel; new 2024 model: "Complete [Species] Food").',
    category: 'IDENTITY',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO PF2(a)(2), PF4(a)',
    appliesWhen: 'Every pet food — species/intended-use must appear on the PDP.',
  },
  {
    slug: 'pet-guaranteed-analysis',
    title: 'Guaranteed Analysis',
    body: 'GUARANTEED ANALYSIS — Crude Protein (min) __%, Crude Fat (min) __%, Crude Fiber (max) __%, Moisture (max) __% (as-fed basis; sliding-scale ranges prohibited). New 2024 model: "Pet Nutrition Facts" box with Total Carbohydrate/Dietary Fiber replacing Crude Fiber.',
    category: 'IDENTITY',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO PF5(a)(3) (legacy GA still valid in ~6-yr discretion window)',
    appliesWhen: 'Every dog/cat food.',
  },
  {
    slug: 'pet-calorie-content',
    title: 'Pet Food Calorie Content Statement',
    body: 'Metabolizable energy (ME) __ kcal/kg, __ kcal/cup (calculated) — ME on an as-fed basis, via Modified Atwater or an AAFCO feeding test.',
    category: 'IDENTITY',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO PF9 + PF5(a)(2)',
    appliesWhen: 'Every dog/cat food.',
  },
  {
    slug: 'pet-ingredient-statement',
    title: 'Pet Food Ingredient Statement',
    body: 'Ingredients: [all ingredients in descending order of predominance by weight, each by its AAFCO-defined or common name].',
    category: 'IDENTITY',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO PF6 + 21 CFR 501.4',
    appliesWhen: 'Every pet food.',
  },
  {
    slug: 'pet-feeding-directions',
    title: 'Pet Food Feeding Directions',
    body: 'Feeding directions stating at minimum the amount of product per body-weight of the animal AND the frequency of feeding (a body-weight table is the standard form). Vet-directed: "Use only as directed by your veterinarian."',
    category: 'DIRECTIONS',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO PF8',
    appliesWhen: 'Required on all dog/cat food labeled complete and balanced.',
  },
  {
    slug: 'pet-manufacturer-name-address',
    title: 'Pet Food Manufacturer / Distributor Name & Address',
    body: '[Business name + address]. If not the manufacturer, qualify with "Manufactured for" or "Distributed by".',
    category: 'IDENTITY',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO PF11 + 21 CFR 501.5',
    appliesWhen: 'Every pet food.',
  },
  {
    slug: 'pet-supplemental-feeding-only',
    title: 'Pet Food "Intermittent or Supplemental Feeding Only"',
    body: 'This product is intended for intermittent or supplemental feeding only.',
    category: 'DISCLAIMER',
    labelingTypes: ['PET_PRODUCT'],
    cfrCitation: 'AAFCO PF5(a)(3)(F)(iii)',
    appliesWhen: 'Product does NOT meet an AAFCO profile/feeding protocol for any life stage. Mutually exclusive with the complete-and-balanced adequacy statement.',
  },

  // ---- Alcohol beverages (TTB — 27 CFR 4/5/7) ----
  {
    slug: 'alcohol-content-statement',
    title: 'Alcohol Content Statement',
    body: 'Alc. [X]% by Vol. (or "[X]% Alc/Vol") — percent alcohol by volume. Spirits may add degrees of proof in the same field of vision.',
    category: 'IDENTITY',
    labelingTypes: ['BEVERAGE'],
    cfrCitation: 'Spirits 27 CFR 5.65; Wine 4.36; Malt 7.65',
    appliesWhen: 'Every alcohol-beverage label (required for spirits/wine; per rule for malt).',
  },
  {
    slug: 'alcohol-class-type-designation',
    title: 'Class / Type Designation',
    body: '[Class and type designation, e.g. "Bourbon Whiskey", "Cabernet Sauvignon", "India Pale Ale"] — shown in the same field of vision as the brand name.',
    category: 'IDENTITY',
    labelingTypes: ['BEVERAGE'],
    cfrCitation: 'Wine 27 CFR 4.32(a); Spirits 5.63(a); Malt 7.63',
    appliesWhen: 'Every alcohol-beverage label.',
  },
  {
    slug: 'alcohol-bottler-importer-name',
    title: 'Bottler / Importer Name & Address',
    body: '[Name & address of bottler/distiller, or "Imported by [name, address]" for imports]. Multi-country spirits require a statement of composition.',
    category: 'IDENTITY',
    labelingTypes: ['BEVERAGE'],
    cfrCitation: 'Spirits 27 CFR 5.63(b)/5.68; Wine 4.32; Malt 7.63',
    appliesWhen: 'Every alcohol-beverage label; "Imported by" applies to imports.',
  },
  {
    slug: 'alcohol-fdc-yellow-5',
    title: 'Alcohol FD&C Yellow No. 5 Declaration',
    body: 'Contains FD&C Yellow No. 5.',
    category: 'IDENTITY',
    labelingTypes: ['BEVERAGE'],
    cfrCitation: '27 CFR 4.32(c)/5.63(c)/7.63(b)(1)',
    appliesWhen: 'Alcohol beverage contains FD&C Yellow No. 5.',
  },
  {
    slug: 'alcohol-cochineal-carmine',
    title: 'Alcohol Cochineal / Carmine Declaration',
    body: 'Contains cochineal extract. (or "Contains carmine".)',
    category: 'IDENTITY',
    labelingTypes: ['BEVERAGE'],
    cfrCitation: '27 CFR 5.63(c)/7.63(b)(2)',
    appliesWhen: 'Alcohol beverage contains the color additive cochineal extract or carmine.',
  },

  // ---- Nutrient-content claims (only if the product meets the FDA threshold) ----
  ...[
    ['high-in-protein', 'High in Protein'],
    ['excellent-source-of-fiber', 'Excellent Source of Fiber'],
    ['low-sugar', 'Low Sugar'],
    ['no-added-sugar', 'No Added Sugar'],
    ['sugar-free', 'Sugar-Free'],
    ['zero-calories', 'Zero Calories'],
    ['zero-trans-fat', '0g Trans Fat'],
    ['naturally-sweetened', 'Naturally Sweetened'],
    ['high-in-vitamin-c', 'High in Vitamin C'],
    ['caffeine-free', 'Caffeine-Free'],
  ].map(([slug, title]): PhraseSeed => ({
    slug: slug!,
    title: title!,
    body: title!,
    category: 'CLAIM',
    requirement: 'RECOMMENDED',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE'],
    cfrCitation: '21 CFR 101.13/101.54 (nutrient content claims)',
    appliesWhen: 'Only if the product meets the FDA threshold for this claim.',
  })),

  // ---- Sustainability (FTC Green Guides — each carries its specific qualifier rule) ----
  ...([
    ['recyclable-packaging', 'Recyclable Packaging', '16 CFR 260.12', 'Unqualified only if recycling facilities reach ≥60% of consumers where sold. Otherwise qualify: "This package may not be recyclable in your area."'],
    ['made-with-recycled-materials', 'Made with Recycled Materials', '16 CFR 260.13', 'Unqualified only if the entire item is recycled; otherwise state %-by-weight, e.g. "Made from 30% recycled material." Pre-consumer content must be substantiated.'],
    ['carbon-neutral-shipping', 'Carbon-Neutral Shipping', '16 CFR 260.5 + 260.4', 'HIGH-RISK. Needs competent scientific + accounting proof; disclose if reductions occur ≥2 years out; cannot count legally-required reductions. No FTC safe-harbor wording.'],
    ['compostable', 'Compostable', '16 CFR 260.7', 'Needs scientific evidence all materials compost safely + timely. Disclose if not home-compostable and if facilities are not available to a substantial majority.'],
    ['biodegradable', 'Biodegradable', '16 CFR 260.8', 'HIGH-RISK. Unqualified claim requires complete breakdown within ~1 year after customary disposal; per se deceptive for items landfilled/incinerated/recycled.'],
    ['non-toxic', 'Non-Toxic', '16 CFR 260.10', 'Conveys non-toxic to BOTH humans AND the environment; needs competent scientific evidence for both, or a clear qualifier.'],
    ['plant-based-ingredients', 'Plant-Based Ingredients', '16 CFR 260.4 (general benefit)', 'Substantiate the % plant-derived; avoid implying a broad unqualified environmental benefit.'],
    ['sustainably-sourced', 'Sustainably Sourced', '16 CFR 260.4', 'HIGH-RISK. FTC declines to define "sustainable" — an unqualified general-benefit claim. Narrow to a specific substantiated attribute.'],
    ['cruelty-free', 'Cruelty-Free', 'FTC §5 (deception)', 'Needs a documented no-animal-testing policy across the supply chain (incl. ingredients + foreign-required testing). Leaping Bunny/PETA are private marks.'],
    ['bpa-free', 'BPA-Free', '16 CFR 260.9 (free-of)', 'HIGH-RISK. Deceptive if a same-risk substitute is used (e.g. BPS) or if BPA was never in this product category.'],
    ['fair-trade-certified', 'Fair Trade Certified', '16 CFR 260.6 + §255', 'Requires a valid certificate from a genuine independent certifier on file before the mark renders.'],
  ] as const).map(([slug, title, cfrCitation, appliesWhen]): PhraseSeed => ({
    slug,
    title,
    body: title,
    category: 'SUSTAINABILITY',
    requirement: 'RECOMMENDED',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'OTC', 'PET_PRODUCT', 'BEVERAGE', 'COSMETIC'],
    cfrCitation,
    appliesWhen,
  })),

  // ---- Substantiation-gated claims (FDA/USDA/FTC governed — cert or threshold required) ----
  ...([
    ['gluten-free', 'Gluten-Free', '21 CFR 101.91', 'FDA-defined: unavoidable gluten <20 ppm. "No gluten"/"free of gluten"/"without gluten" trigger the same standard. If wheat is an ingredient, add the "processed to meet FDA gluten-free requirements" statement.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE']],
    ['organic', 'Organic', 'USDA NOP — 7 CFR Part 205', 'A CERTIFICATION, not a free claim. "Organic"/"100% organic"/"made with organic" require a USDA-accredited certifier. Gate behind a valid certificate.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE', 'COSMETIC']],
    ['non-gmo', 'Non-GMO', 'USDA NBFDS 7 CFR 66 + FTC §5', 'Voluntary "Non-GMO" needs substantiation; "Non-GMO Project Verified" is a private mark. Note: mandatory bioengineered disclosure may still apply.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE']],
    ['all-natural', 'All Natural', 'FDA policy + FTC §5', 'HIGH litigation risk. FDA has no formal definition; longstanding policy = nothing artificial/synthetic added that would not normally be expected. Substantiate.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE']],
    ['vegan', 'Vegan', 'No FDA/FTC definition — §5', 'Substantiation = no animal-derived ingredients or processing aids.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE', 'COSMETIC']],
    ['keto-friendly', 'Keto-Friendly', 'FDA — not an authorized claim', 'HIGH-RISK. "Low carb"/"keto" are not FDA-defined nutrient-content claims; high warning-letter/deception risk.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE']],
    ['kosher', 'Kosher', 'Private certification (+ state laws)', 'Requires a valid kosher certification; not a government standard.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE']],
    ['halal', 'Halal', 'Private certification', 'Requires a valid halal certification; not a government standard.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE']],
    ['made-in-usa', 'Made in USA', '16 CFR Part 323 (enforceable rule)', 'HIGH-RISK — civil penalties. Requires "all or virtually all" of the product made + sourced in the US, final + significant processing in the US. Use qualified claims otherwise.', ['FOOD', 'DIETARY_SUPPLEMENT', 'OTC', 'PET_PRODUCT', 'BEVERAGE', 'COSMETIC']],
    ['hypoallergenic', 'Hypoallergenic', 'No FDA standard — §5', 'No FDA definition; substantiate the reduced-allergen basis.', ['COSMETIC']],
    ['dermatologist-tested', 'Dermatologist Tested', '16 CFR 255.3 (expert endorsement)', 'Requires real evaluation by qualified dermatologist(s) + disclosure of any material connection (255.5).', ['COSMETIC']],
  ] as const).map(([slug, title, cfrCitation, appliesWhen, lt]): PhraseSeed => ({
    slug,
    title,
    body: title,
    category: 'CLAIM',
    requirement: 'RECOMMENDED',
    labelingTypes: lt as unknown as string[],
    cfrCitation,
    appliesWhen,
  })),

  // ---- Storage & usage directions ----
  ...[
    ['storage-do-not-freeze', 'Do Not Freeze', 'Do not freeze.'],
    ['storage-below-25c', 'Store Below 25°C', 'Store below 25°C (77°F).'],
    ['storage-use-within-14-days', 'Use Within 14 Days', 'Use within 14 days of opening.'],
    ['storage-shake-well', 'Shake Well Before Use', 'Shake well before use.'],
    ['storage-best-within-30-days', 'Best Within 30 Days', 'Best consumed within 30 days of opening.'],
    ['storage-avoid-sunlight', 'Avoid Direct Sunlight', 'Avoid direct sunlight.'],
    ['usage-mix-powder', 'Mix Directions (Powder)', 'Mix one scoop with 8 fl oz of cold water.'],
    ['usage-capsule-dose', 'Dosage (Capsule)', 'Take [N] capsules daily with food.'],
    ['usage-best-cold', 'Best Enjoyed Cold', 'Best enjoyed cold.'],
    ['usage-ready-to-drink', 'Ready to Drink', 'Ready to drink — no mixing required.'],
    ['usage-serving-suggestion', 'Serving Suggestion', 'Add to smoothies, yogurt, or oats.'],
  ].map(([slug, title, body]): PhraseSeed => ({
    slug: slug!,
    title: title!,
    body: body!,
    category: 'DIRECTIONS',
    requirement: 'RECOMMENDED',
    labelingTypes: ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE'],
  })),

  // ---- Marketing / audience ----
  ...[
    ['not-for-children-under-18', 'Not for Children Under 18', 'Not intended for children under 18.', ['DIETARY_SUPPLEMENT']],
    ['allergen-free-facility', 'Allergen-Free Facility', 'Produced in an allergen-free facility.', ['FOOD', 'DIETARY_SUPPLEMENT']],
    ['drink-responsibly', 'Drink Responsibly', 'Please drink responsibly.', ['BEVERAGE']],
    ['21-plus-id-required', '21+ · ID Required', '21+ · ID required.', ['BEVERAGE']],
    ['please-recycle', 'Please Recycle', 'Please recycle.', ['FOOD', 'DIETARY_SUPPLEMENT', 'OTC', 'PET_PRODUCT', 'BEVERAGE', 'COSMETIC']],
    ['for-ages-6-months', 'For Ages 6+ Months', 'For ages 6+ months.', ['FOOD']],
    ['pediatrician-recommended', 'Pediatrician Recommended', 'Pediatrician recommended.', ['FOOD', 'DIETARY_SUPPLEMENT']],
    ['no-artificial-colors-flavors', 'No Artificial Colors or Flavors', 'No artificial colors or flavors.', ['FOOD', 'DIETARY_SUPPLEMENT', 'BEVERAGE']],
    ['first-foods', 'First Foods', 'First foods.', ['FOOD']],
    ['for-sensitive-skin', 'For Sensitive Skin', 'For sensitive skin.', ['COSMETIC']],
  ].map(([slug, title, body, lt]): PhraseSeed => ({
    slug: slug as string,
    title: title as string,
    body: body as string,
    category: 'MARKETING',
    requirement: 'RECOMMENDED',
    labelingTypes: lt as string[],
  })),
]

export async function seedMandatoryPhrases(prisma: PrismaClient): Promise<void> {
  for (let i = 0; i < PHRASES.length; i++) {
    const p = PHRASES[i]!
    await prisma.mandatoryPhrase.upsert({
      where: { slug: p.slug },
      create: {
        slug: p.slug,
        title: p.title,
        body: p.body,
        category: p.category,
        requirement: p.requirement ?? 'MANDATORY',
        labelingTypes: p.labelingTypes,
        cfrCitation: p.cfrCitation ?? null,
        appliesWhen: p.appliesWhen ?? null,
        displayOrder: i,
        isActive: true,
      },
      update: {
        title: p.title,
        body: p.body,
        category: p.category,
        requirement: p.requirement ?? 'MANDATORY',
        labelingTypes: p.labelingTypes,
        cfrCitation: p.cfrCitation ?? null,
        appliesWhen: p.appliesWhen ?? null,
        displayOrder: i,
      },
    })
  }
  // eslint-disable-next-line no-console
  console.log(`  ✓ Seeded ${PHRASES.length} mandatory phrases`)
}

// Standalone run: `tsx prisma/seed-mandatory-phrases.ts`
if (process.argv[1]?.endsWith('seed-mandatory-phrases.ts')) {
  const prisma = new PrismaClient()
  seedMandatoryPhrases(prisma)
    .catch((e) => {
      // eslint-disable-next-line no-console
      console.error(e)
      process.exit(1)
    })
    .finally(() => prisma.$disconnect())
}
