"""Prisma Python client singleton.

Generated by `prisma generate` from the shared schema at
packages/db/prisma/schema.prisma (see pyproject.toml [tool.prisma]).

Output lands at services/compliance/.prisma_py/ — already gitignored.
"""
from __future__ import annotations

# Generated client. Run `prisma generate` from services/compliance/
# before the first import.
# The Prisma client is generated by `prisma generate` (not run in CI/lint), so
# the symbol is absent to the type checker — suppress attr-defined, treat as Any.
from prisma import Prisma  # type: ignore[attr-defined]

_prisma: Prisma | None = None


async def get_prisma() -> Prisma:
    global _prisma
    if _prisma is None:
        _prisma = Prisma()
    if not _prisma.is_connected():
        await _prisma.connect()
    return _prisma


async def disconnect_prisma() -> None:
    global _prisma
    if _prisma is not None and _prisma.is_connected():
        await _prisma.disconnect()
        _prisma = None
