import type { ProductCardProps } from '@ilaunchify/ui'

/**
 * Sample marketplace data for the V1 render. Replaced by a real DB query
 * (Prisma ProductTemplate where marketplaceStatus = PUBLISHED) once the
 * apps/marketing app gets wired to the database in DS-11+.
 */

export type SampleTemplate = Omit<ProductCardProps, 'href'> & {
  slug: string
  categorySlug: string
  subcategorySlug?: string
}

function href(t: { categorySlug: string; subcategorySlug?: string; slug: string }) {
  // Route is /marketplace/[category]/[subcategory]/[slug] — when a template
  // doesn't carry a subcategory, fall back to `all` so the URL still resolves.
  return `/marketplace/${t.categorySlug}/${t.subcategorySlug ?? 'all'}/${t.slug}`
}

export const COFFEE_TEA: SampleTemplate[] = [
  {
    slug: 'colombian-single-origin',
    categorySlug: 'coffee-tea',
    subcategorySlug: 'whole-bean',
    title: 'Colombian Single-Origin',
    niche: 'Coffee & Tea',
    status: 'bestseller',
    icon: '☕',
    gradient: 'mint',
    tags: [
      { label: 'USDA Organic', organic: true },
      { label: 'Fair Trade' },
      { label: 'Vegan' },
    ],
    minUnits: 100,
    leadTimeDays: 12,
    pricePerUnit: 3.9,
  },
  {
    slug: 'cold-brew-concentrate',
    categorySlug: 'coffee-tea',
    title: 'Cold Brew Concentrate',
    niche: 'Coffee & Tea',
    status: 'top-rated',
    icon: '🧋',
    gradient: 'coral',
    tags: [{ label: 'Vegan' }, { label: 'Non-GMO' }],
    minUnits: 250,
    leadTimeDays: 10,
    pricePerUnit: 4.1,
  },
  {
    slug: 'matcha-ceremonial-grade',
    categorySlug: 'coffee-tea',
    title: 'Matcha Ceremonial Grade',
    niche: 'Coffee & Tea',
    status: 'fast-ship',
    icon: '🍵',
    gradient: 'lime',
    tags: [{ label: 'USDA Organic', organic: true }, { label: 'Vegan' }],
    minUnits: 150,
    leadTimeDays: 8,
    pricePerUnit: 6.8,
  },
  {
    slug: 'adaptogenic-herbal-tea',
    categorySlug: 'coffee-tea',
    title: 'Adaptogenic Herbal Tea',
    niche: 'Coffee & Tea',
    status: 'low-moq',
    icon: '🌼',
    gradient: 'yellow',
    tags: [{ label: 'USDA Organic', organic: true }, { label: 'Caffeine-free' }],
    minUnits: 50,
    leadTimeDays: 7,
    pricePerUnit: 2.9,
  },
  {
    slug: 'rose-hibiscus-bloom',
    categorySlug: 'coffee-tea',
    title: 'Rose Hibiscus Bloom',
    niche: 'Coffee & Tea',
    status: 'new',
    icon: '🌹',
    gradient: 'pink',
    tags: [{ label: 'Vegan' }, { label: 'Caffeine-free' }],
    minUnits: 200,
    leadTimeDays: 9,
    pricePerUnit: 4.5,
  },
]

export const FUNCTIONAL_BEVERAGES: SampleTemplate[] = [
  {
    slug: 'sparkling-botanical-water',
    categorySlug: 'functional-beverages',
    title: 'Sparkling Botanical Water',
    niche: 'Functional Beverages',
    status: 'top-rated',
    icon: '🫧',
    gradient: 'cyan',
    tags: [{ label: 'USDA Organic', organic: true }, { label: 'Vegan' }],
    minUnits: 500,
    leadTimeDays: 6,
    pricePerUnit: 1.95,
  },
  {
    slug: 'electrolyte-hydration-mix',
    categorySlug: 'functional-beverages',
    title: 'Electrolyte Hydration Mix',
    niche: 'Functional Beverages',
    status: 'fast-ship',
    icon: '⚡',
    gradient: 'sky',
    tags: [{ label: 'Sugar-free' }, { label: 'NSF' }],
    minUnits: 250,
    leadTimeDays: 5,
    pricePerUnit: 2.4,
  },
  {
    slug: 'mushroom-coffee-blend',
    categorySlug: 'functional-beverages',
    title: 'Mushroom Coffee Blend',
    niche: 'Functional Beverages',
    status: 'bestseller',
    icon: '🍄',
    gradient: 'mint',
    tags: [{ label: 'USDA Organic', organic: true }, { label: 'Adaptogenic' }],
    minUnits: 150,
    leadTimeDays: 9,
    pricePerUnit: 5.2,
  },
  {
    slug: 'rtd-botanical-aperitif',
    categorySlug: 'functional-beverages',
    title: 'RTD Botanical Aperitif',
    niche: 'Functional Beverages',
    status: 'new',
    icon: '🍸',
    gradient: 'coral',
    tags: [{ label: 'Vegan' }, { label: 'Low-cal' }],
    minUnits: 300,
    leadTimeDays: 11,
    pricePerUnit: 3.8,
  },
  {
    slug: 'vitamin-c-sparkler',
    categorySlug: 'functional-beverages',
    title: 'Vitamin C Sparkler',
    niche: 'Functional Beverages',
    status: 'popular',
    icon: '🍊',
    gradient: 'yellow',
    tags: [{ label: 'Sugar-free' }, { label: 'Vegan' }],
    minUnits: 400,
    leadTimeDays: 7,
    pricePerUnit: 2.1,
  },
]

export const SUPPLEMENTS: SampleTemplate[] = [
  {
    slug: 'adaptogen-powder-blend',
    categorySlug: 'supplements',
    title: 'Adaptogen Powder Blend',
    niche: 'Supplements',
    status: 'bestseller',
    icon: '🌿',
    gradient: 'lime',
    tags: [
      { label: 'USDA Organic', organic: true },
      { label: 'Vegan' },
      { label: 'Non-GMO' },
    ],
    minUnits: 200,
    leadTimeDays: 7,
    pricePerUnit: 8.4,
  },
  {
    slug: 'magnesium-glycinate',
    categorySlug: 'supplements',
    title: 'Magnesium Glycinate',
    niche: 'Supplements',
    status: 'top-rated',
    icon: '💊',
    gradient: 'purple',
    tags: [{ label: 'cGMP' }, { label: 'Non-GMO' }],
    minUnits: 200,
    leadTimeDays: 6,
    pricePerUnit: 5.1,
  },
  {
    slug: 'adaptogenic-mushroom-caps',
    categorySlug: 'supplements',
    title: 'Adaptogenic Mushroom Caps',
    niche: 'Supplements',
    status: 'fast-ship',
    icon: '🍄',
    gradient: 'mint',
    tags: [{ label: 'USDA Organic', organic: true }, { label: 'Vegan' }],
    minUnits: 250,
    leadTimeDays: 7,
    pricePerUnit: 8.4,
  },
  {
    slug: 'daily-greens-powder',
    categorySlug: 'supplements',
    title: 'Daily Greens Powder',
    niche: 'Supplements',
    status: 'low-moq',
    icon: '🥬',
    gradient: 'yellow',
    tags: [{ label: 'USDA Organic', organic: true }, { label: 'Vegan' }],
    minUnits: 50,
    leadTimeDays: 9,
    pricePerUnit: 6.9,
  },
  {
    slug: 'collagen-berry-drink',
    categorySlug: 'supplements',
    title: 'Collagen Berry Drink',
    niche: 'Supplements',
    status: 'new',
    icon: '🍓',
    gradient: 'pink',
    tags: [{ label: 'High-protein' }, { label: 'Sugar-free' }],
    minUnits: 250,
    leadTimeDays: 8,
    pricePerUnit: 3.4,
  },
]

export const SNACKS: SampleTemplate[] = [
  {
    slug: 'protein-bar-triple-choc',
    categorySlug: 'snacks',
    title: 'Protein Bar — Triple Choc',
    niche: 'Snacks',
    status: 'popular',
    icon: '🍫',
    gradient: 'coral',
    tags: [{ label: 'High-protein' }, { label: 'Gluten-free' }],
    minUnits: 500,
    leadTimeDays: 8,
    pricePerUnit: 2.1,
  },
  {
    slug: 'functional-gummies',
    categorySlug: 'snacks',
    title: 'Functional Gummies',
    niche: 'Snacks',
    status: 'top-rated',
    icon: '🍬',
    gradient: 'purple',
    tags: [{ label: 'Vegan' }, { label: 'Sugar-free' }],
    minUnits: 300,
    leadTimeDays: 11,
    pricePerUnit: 3.4,
  },
  {
    slug: 'keto-granola-clusters',
    categorySlug: 'snacks',
    title: 'Keto Granola Clusters',
    niche: 'Snacks',
    status: 'low-moq',
    icon: '🥣',
    gradient: 'yellow',
    tags: [{ label: 'USDA Organic', organic: true }, { label: 'Keto' }],
    minUnits: 50,
    leadTimeDays: 9,
    pricePerUnit: 4.8,
  },
  {
    slug: 'sea-salt-pretzel-bites',
    categorySlug: 'snacks',
    title: 'Sea Salt Pretzel Bites',
    niche: 'Snacks',
    status: 'fast-ship',
    icon: '🥨',
    gradient: 'blush',
    tags: [{ label: 'Vegan' }, { label: 'Non-GMO' }],
    minUnits: 400,
    leadTimeDays: 6,
    pricePerUnit: 2.6,
  },
  {
    slug: 'cassava-cookie-bites',
    categorySlug: 'snacks',
    title: 'Cassava Cookie Bites',
    niche: 'Snacks',
    status: 'bestseller',
    icon: '🍪',
    gradient: 'mint',
    tags: [{ label: 'Gluten-free' }, { label: 'Paleo' }],
    minUnits: 250,
    leadTimeDays: 8,
    pricePerUnit: 3.2,
  },
]

export const CATEGORY_ROWS = [
  { title: 'Coffee & Tea', slug: 'coffee-tea', templates: COFFEE_TEA },
  { title: 'Functional & Wellness Beverages', slug: 'functional-beverages', templates: FUNCTIONAL_BEVERAGES },
  { title: 'Supplements', slug: 'supplements', templates: SUPPLEMENTS },
  { title: 'Snacks & Confectionery', slug: 'snacks', templates: SNACKS },
] as const

export function templateToCardProps(t: SampleTemplate): ProductCardProps {
  return { ...t, href: href(t) }
}
