// Color harmony generation for the Brand Palette Generator.
// Pure HSL hue-rotation math — deterministic with a seed, lock-aware. No IP.

import { hexToHsl, hslToHex, normalizeHex, type Hsl } from './convert'

export type HarmonyMethod =
  | 'AUTO'
  | 'MONOCHROMATIC'
  | 'ANALOGOUS'
  | 'COMPLEMENTARY'
  | 'SPLIT_COMPLEMENTARY'
  | 'TRIADIC'
  | 'TETRADIC'
  | 'SQUARE'

export const HARMONY_METHODS: { value: HarmonyMethod; label: string; pro: boolean }[] = [
  { value: 'AUTO', label: 'Auto', pro: false },
  { value: 'MONOCHROMATIC', label: 'Monochromatic', pro: true },
  { value: 'ANALOGOUS', label: 'Analogous', pro: true },
  { value: 'COMPLEMENTARY', label: 'Complementary', pro: true },
  { value: 'SPLIT_COMPLEMENTARY', label: 'Split complementary', pro: true },
  { value: 'TRIADIC', label: 'Triadic', pro: true },
  { value: 'TETRADIC', label: 'Tetradic', pro: true },
  { value: 'SQUARE', label: 'Square', pro: true },
]

const HUE_OFFSETS: Record<Exclude<HarmonyMethod, 'AUTO' | 'MONOCHROMATIC'>, number[]> = {
  ANALOGOUS: [0, 30, -30, 60, -60, 90],
  COMPLEMENTARY: [0, 180],
  SPLIT_COMPLEMENTARY: [0, 150, 210],
  TRIADIC: [0, 120, 240],
  TETRADIC: [0, 60, 180, 240],
  SQUARE: [0, 90, 180, 270],
}

/** Deterministic PRNG (mulberry32) — seeded for tests, else seeded from time. */
function rng(seed?: number): () => number {
  let a = (seed ?? (Date.now() & 0xffffffff)) >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const clamp = (n: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, n))

export interface GenerateOptions {
  method: HarmonyMethod
  count: number // 2–6
  base?: string // optional seed hex; else random
  locked?: (string | null)[] // per-slot lock; null = regenerate this slot
  seed?: number // deterministic for tests
}

/**
 * Generate a palette of `count` hex colors. Locked slots are preserved verbatim;
 * `null` slots are (re)generated by the chosen method around a base hue.
 */
export function generatePalette(opts: GenerateOptions): string[] {
  const count = clamp(Math.round(opts.count), 2, 6)
  const rand = rng(opts.seed)
  const locked = opts.locked ?? []

  // Base hue: from `base`, else from the first locked color, else random.
  const firstLocked = locked.find((c): c is string => !!c && !!normalizeHex(c))
  const baseHsl: Hsl =
    opts.base && normalizeHex(opts.base)
      ? hexToHsl(opts.base)
      : firstLocked
        ? hexToHsl(firstLocked)
        : { h: Math.floor(rand() * 360), s: 55 + Math.floor(rand() * 30), l: 48 + Math.floor(rand() * 14) }

  const gen = (i: number): string => {
    if (opts.method === 'AUTO') {
      return hslToHex({
        h: Math.floor(rand() * 360),
        s: 45 + Math.floor(rand() * 40),
        l: 35 + Math.floor(rand() * 40),
      })
    }
    if (opts.method === 'MONOCHROMATIC') {
      // Same hue; spread lightness across the slots, small saturation jitter.
      const l = count === 1 ? baseHsl.l : Math.round(22 + (i / (count - 1)) * 60)
      const s = clamp(baseHsl.s + Math.round((rand() - 0.5) * 12), 10, 95)
      return hslToHex({ h: baseHsl.h, s, l })
    }
    const offsets = HUE_OFFSETS[opts.method]
    const offset = offsets[i % offsets.length] ?? 0
    const cycle = Math.floor(i / offsets.length)
    // Extra slots beyond the method's natural size step lightness so they stay distinct.
    const l = clamp(baseHsl.l + cycle * 14, 20, 82)
    const s = clamp(baseHsl.s + Math.round((rand() - 0.5) * 8), 15, 95)
    return hslToHex({ h: (baseHsl.h + offset + 360) % 360, s, l })
  }

  const out: string[] = []
  for (let i = 0; i < count; i++) {
    const lock = locked[i]
    const norm = lock ? normalizeHex(lock) : null
    out.push(norm ?? gen(i))
  }
  return out
}
