-- AlterEnum
ALTER TYPE "NotificationEvent" ADD VALUE 'CERT_EXPIRING_SOON';
ALTER TYPE "NotificationEvent" ADD VALUE 'CERT_EXPIRED';
ALTER TYPE "NotificationEvent" ADD VALUE 'ADMIN_CERT_EXPIRED_ON_PUBLISHED';
