'use client'

// Side-by-side die-line curator (Slice C9.g).
//   • Left  — the partner's ORIGINAL file, read-only (never edited).
//   • Right — the live NORMALIZED preview, regenerated from the structured spec
//             as the admin edits trim / bleed / safe values.
// Saving regenerates + stores the normalized SVG and marks the die-line
// ADMIN_VERIFIED + ACTIVE.

import { useMemo, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { CheckCircle2, FileWarning, ShieldCheck } from 'lucide-react'
import { dielineSvgFromSpec, type DielineFold, type DielineSurface } from '@ilaunchify/ui'
import { curateDieline } from '../actions'

interface Spec {
  widthMm: number
  heightMm: number
  bleedMm: number
  safeAreaMm: number
}

interface Props {
  dielineId: string
  status: string
  initial: Spec
  foldLines: Array<{ x1: number; y1: number; x2: number; y2: number; type?: string }> | null
  surfaces: Array<{ name: string; trimBox?: { x: number; y: number; w: number; h: number } | null }> | null
  original: { url: string; contentType: string; filename: string } | null
}

export function DielineCurator({ dielineId, status, initial, foldLines, surfaces, original }: Props) {
  const router = useRouter()
  const [pending, start] = useTransition()
  const [spec, setSpec] = useState<Spec>(initial)

  const canSave = status === 'PARTNER_CONFIRMED' || status === 'ACTIVE'
  const valid =
    spec.widthMm > 0 &&
    spec.heightMm > 0 &&
    spec.bleedMm >= 0 &&
    spec.safeAreaMm >= 0 &&
    spec.safeAreaMm * 2 < spec.widthMm &&
    spec.safeAreaMm * 2 < spec.heightMm

  const svg = useMemo(() => {
    if (!valid) return ''
    return dielineSvgFromSpec({
      widthMm: spec.widthMm,
      heightMm: spec.heightMm,
      bleedMm: spec.bleedMm,
      safeAreaMm: spec.safeAreaMm,
      foldLines: (foldLines as DielineFold[] | null) ?? undefined,
      surfaces: (surfaces as DielineSurface[] | null) ?? undefined,
    })
  }, [spec, valid, foldLines, surfaces])

  function save() {
    if (!valid) {
      toast.error('Check the trim, bleed and safe values.')
      return
    }
    start(async () => {
      const r = await curateDieline({
        dielineId,
        widthMm: spec.widthMm,
        heightMm: spec.heightMm,
        bleedMm: spec.bleedMm,
        safeAreaMm: spec.safeAreaMm,
      })
      if (!r.ok) {
        toast.error(r.error)
        return
      }
      toast.success('Normalized & verified')
      router.push('/dielines')
      router.refresh()
    })
  }

  return (
    <div className="space-y-5">
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <Panel title="Partner original" subtitle="Reference only — never modified">
          <OriginalPreview original={original} />
        </Panel>

        <Panel title="Normalized preview" subtitle="Regenerated live from the spec below">
          <div className="flex min-h-[260px] items-center justify-center rounded-xl border border-ink-100 bg-[repeating-conic-gradient(#f4f4f5_0%_25%,#fff_0%_50%)] bg-[length:16px_16px] p-4">
            {svg ? (
              <div
                className="w-full max-w-[420px] [&_svg]:h-auto [&_svg]:w-full"
                // SVG is generated by our own pure function from numeric inputs — no user HTML.
                dangerouslySetInnerHTML={{ __html: svg }}
              />
            ) : (
              <p className="text-[12.5px] text-ink-400">Enter valid trim dimensions to preview.</p>
            )}
          </div>
        </Panel>
      </div>

      <div className="rounded-2xl border border-ink-200 bg-white p-5">
        <div className="flex items-center gap-2">
          <ShieldCheck className="h-4 w-4 text-pink-600" />
          <h2 className="text-[13.5px] font-bold text-ink-900">Standardize the spec</h2>
        </div>
        <p className="mt-1 text-[12px] text-ink-500">
          Trim, bleed and safe area are normalized to the house standard. Fold lines and named surfaces from the
          partner are preserved as-is.
        </p>

        <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <NumberField
            label="Trim width (mm)"
            value={spec.widthMm}
            onChange={(v) => setSpec((s) => ({ ...s, widthMm: v }))}
          />
          <NumberField
            label="Trim height (mm)"
            value={spec.heightMm}
            onChange={(v) => setSpec((s) => ({ ...s, heightMm: v }))}
          />
          <NumberField
            label="Bleed (mm)"
            value={spec.bleedMm}
            onChange={(v) => setSpec((s) => ({ ...s, bleedMm: v }))}
          />
          <NumberField
            label="Safe inset (mm)"
            value={spec.safeAreaMm}
            onChange={(v) => setSpec((s) => ({ ...s, safeAreaMm: v }))}
          />
        </div>

        {!valid && (
          <p className="mt-3 inline-flex items-center gap-1.5 text-[12px] font-medium text-amber-700">
            <FileWarning className="h-3.5 w-3.5" /> Width and height must be positive; safe inset must fit inside the trim.
          </p>
        )}

        <div className="mt-5 flex items-center justify-between gap-3">
          <p className="text-[11.5px] text-ink-400">
            The original file stays immutable. Saving stores a normalized copy and stamps the die-line verified.
          </p>
          <button
            onClick={save}
            disabled={pending || !valid || !canSave}
            className="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-emerald-600 px-4 py-1.5 text-[12.5px] font-semibold text-white hover:bg-emerald-700 disabled:opacity-50"
          >
            <CheckCircle2 className="h-4 w-4" />
            {pending ? 'Saving…' : 'Save normalized & verify'}
          </button>
        </div>
      </div>
    </div>
  )
}

function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return (
    <section className="overflow-hidden rounded-2xl border border-ink-200 bg-white">
      <div className="border-b border-ink-100 bg-zinc-50/60 px-4 py-2.5">
        <p className="text-[12.5px] font-bold text-ink-800">{title}</p>
        <p className="text-[11px] text-ink-500">{subtitle}</p>
      </div>
      <div className="p-4">{children}</div>
    </section>
  )
}

function OriginalPreview({ original }: { original: Props['original'] }) {
  if (!original) {
    return (
      <div className="flex min-h-[260px] items-center justify-center rounded-xl border border-dashed border-ink-200 bg-ink-50/40 text-center">
        <p className="px-6 text-[12.5px] text-ink-400">No original file is attached to this die-line.</p>
      </div>
    )
  }
  const ct = original.contentType.toLowerCase()
  const isImage = ct.startsWith('image/')
  const isPdf = ct.includes('pdf')

  return (
    <div className="space-y-2">
      <div className="flex min-h-[260px] items-center justify-center overflow-hidden rounded-xl border border-ink-100 bg-zinc-50">
        {isImage ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={original.url} alt={original.filename} className="max-h-[360px] w-full object-contain" />
        ) : isPdf ? (
          <iframe src={original.url} title={original.filename} className="h-[360px] w-full" />
        ) : (
          <a
            href={original.url}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-full border border-ink-200 bg-white px-3 py-1.5 text-[12px] font-semibold text-ink-700 hover:bg-ink-50"
          >
            Open {original.filename}
          </a>
        )}
      </div>
      <p className="truncate text-[11px] text-ink-400">{original.filename}</p>
    </div>
  )
}

function NumberField({
  label,
  value,
  onChange,
}: {
  label: string
  value: number
  onChange: (v: number) => void
}) {
  return (
    <label className="block">
      <span className="mb-1 block text-[11px] font-semibold uppercase tracking-wider text-ink-500">{label}</span>
      <input
        type="number"
        min={0}
        step={0.5}
        value={Number.isFinite(value) ? value : ''}
        onChange={(e) => onChange(Number(e.target.value))}
        className="w-full rounded-lg border border-ink-200 bg-white px-2.5 py-1.5 text-[13px] text-ink-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-500"
      />
    </label>
  )
}
