-- AlterEnum
ALTER TYPE "NotificationEvent" ADD VALUE 'CREATOR_DISPATCH_ACCEPTED';
ALTER TYPE "NotificationEvent" ADD VALUE 'CREATOR_DISPATCH_CHANGES_REQUESTED';
ALTER TYPE "NotificationEvent" ADD VALUE 'CREATOR_DISPATCH_DECLINED';
ALTER TYPE "NotificationEvent" ADD VALUE 'CREATOR_DISPATCH_WITHDRAWN';
ALTER TYPE "NotificationEvent" ADD VALUE 'CREATOR_ORDER_FULLY_ACCEPTED';
ALTER TYPE "NotificationEvent" ADD VALUE 'CREATOR_ORDER_CANCELLED_BY_MANUFACTURER';
ALTER TYPE "NotificationEvent" ADD VALUE 'ADMIN_ORDER_CANCELLED_BY_MANUFACTURER';
ALTER TYPE "NotificationEvent" ADD VALUE 'ADMIN_DISPATCH_WITHDRAWN';
